services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - aatis_core

  php:
    build:
      context: .boing/docker/php
      args:
        PHP_VERSION: "8.4"
    networks:
      - aatis_core
    volumes:
      - .:/srv

  web:
    depends_on:
      - php
    build:
      context: .boing/docker/nginx/aatis
    networks:
      - aatis_core
    volumes:
      - ./public:/srv/public

networks:
  aatis_core:

volumes:
  db_data:
