exclude_paths:
  - /Kernel.php
  - /Entity

include_services:
  - Aatis\Tester\Common\Service\Writer
  - Aatis\Tester\EventDispatcher\Listener\CustomListener
  - Aatis\Tester\EventDispatcher\Subscriber\CustomSubscriber
  - Aatis\Tester\TemplateRenderer\Service\ExtraRenderer
  - Aatis\Tester\Cache\Service\CacheTestPool

services:
  Aatis\Tester\Common\Service\Writer:
    arguments:
      defaultMessage: "Hello World !"

  Aatis\ErrorHandler\Service\ExceptionCodeBag:
    arguments:
      extraExceptionCodeEnums:
        - Aatis\Tester\ErrorHandler\ExtraExceptionCodeEnum

  Aatis\Tester\EventDispatcher\Listener\CustomListener:
    tags:
      - "event-listener"
      - { tag: "custom-tag", priority: 10 }

